version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sdp2-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdp2
    ports:
      - "5432:5432"
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_EMBEDDEDDATABASE_ENABLED=true # Abd'qe`1``23232